receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp:
    endpoint: "tempo:4317"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ logging, otlp ]
