server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: server
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
      - labels:
          stream:
      - timestamp:
          source: time
          format: RFC3339
    relabel_configs:
      - source_labels: [ __meta_docker_container_name ]
        target_label: container
        replacement: $1
      - action: replace
        source_labels: [ container ]
        target_label: job
        replacement: server

  - job_name: client
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
      - labels:
          stream:
      - timestamp:
          source: time
          format: RFC3339
    relabel_configs:
      - source_labels: [ __meta_docker_container_name ]
        regex: ^/lb-client.*$
        target_label: container
        replacement: $1
      - action: replace
        source_labels: [ container ]
        target_label: job
        replacement: client

  - job_name: rabbitmq
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
      - labels:
          stream:
      - timestamp:
          source: time
          format: RFC3339
    relabel_configs:
      - source_labels: [ __meta_docker_container_name ]
        target_label: container
        replacement: $1
      - action: replace
        source_labels: [ container ]
        target_label: job
        replacement: rabbitmq


#server:
#  http_listen_port: 9080
#  grpc_listen_port: 0
#
#positions:
#  filename: /tmp/positions.yaml
#
#clients:
#  - url: http://loki:3100/loki/api/v1/push
#
#scrape_configs:
#  - job_name: server
#    docker_sd_configs:
#      - host: unix:///var/run/docker.sock
#    pipeline_stages:
#      - json:
#          expressions:
#            stream: stream
#            log: log
#      - labels:
#          stream:
#      - timestamp:
#          source: time
#          format: RFC3339
#    relabel_configs:
#      - source_labels: [ __meta_docker_container_name ]
#        target_label: container
#        replacement: $1
#
#  - job_name: client1
#    docker_sd_configs:
#      - host: unix:///var/run/docker.sock
#    pipeline_stages:
#      - json:
#          expressions:
#            stream: stream
#            log: log
#      - labels:
#          stream:
#      - timestamp:
#          source: time
#          format: RFC3339
#    relabel_configs:
#      - source_labels: [ __meta_docker_container_name ]
#        target_label: container
#        replacement: $1
#
#  - job_name: rabbitmq
#    docker_sd_configs:
#      - host: unix:///var/run/docker.sock
#    pipeline_stages:
#      - json:
#          expressions:
#            stream: stream
#            log: log
#      - labels:
#          stream:
#      - timestamp:
#          source: time
#          format: RFC3339
#    relabel_configs:
#      - source_labels: [ __meta_docker_container_name ]
#        target_label: container
#        replacement: $1